// <auto-generated />
namespace ProjectOfDictionaryWithNetMvc.Dal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig_contents_statusadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_contents_statusadded));
        
        string IMigrationMetadata.Id
        {
            get { return "202206291016388_mig_contents_statusadded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
